name: BuildTest
on: workflow_dispatch
permissions:
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build term
      run: |
        cd term && docker build . -t apk
        docker run --rm apk > term-unsigned.apk
    - name: sign term
      env:
        KS: ${{ secrets.KS }}
        KP: ${{ secrets.KP }}
      run: |
        echo "$KS" | base64 -d > /tmp/signer.jks
        sudo apt update && sudo apt install -y zipalign apksigner
        zipalign -f -v -p 4 term-unsigned.apk term-unsigned-aligned.apk
        apksigner sign --ks /tmp/signer.jks --ks-pass "$KP" --out term.apk term-unsigned-aligned.apk
    - name: upload
      uses: actions/upload-pages-artifact@v3
      with:
          path: '.'
    - name: deploy
      uses: actions/deploy-pages@v4
